# Generated by Django 4.1.7 on 2023-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('published', models.BooleanField(default=True)),
                ('description', models.TextField(default="haven't")),
                ('modified', models.DateTimeField()),
                ('images', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Комикс',
                'verbose_name_plural': 'Комиксы',
            },
        ),
    ]
