# Generated by Django 4.1.7 on 2023-03-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='description',
            field=models.TextField(blank=True, default="haven't"),
        ),
    ]
