# Generated by Django 4.1.7 on 2023-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicbook',
            options={'verbose_name': 'Комикс', 'verbose_name_plural': 'Комиксы'},
        ),
        migrations.AddField(
            model_name='comicbook',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
